### ISSUE TITLE
 Error about device_state_attributes

### ISSUE THREAD

**Issue by the-cyberspace** [metbril/home-assistant-brandstofprijzen#15]
After upgrading to 2021.12.b2 I'm seeing this warning in my logs:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 7 december 2021 19:07:28 (4 occurrences)
Last logged: 7 december 2021 19:07:29

Entity sensor.adviesprijs_euro95 (<class 'custom_components.brandstofprijzen.sensor.BrandstofprijzenSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.adviesprijs_diesel (<class 'custom_components.brandstofprijzen.sensor.BrandstofprijzenSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.adviesprijs_lpg (<class 'custom_components.brandstofprijzen.sensor.BrandstofprijzenSensor'>) implements device_state_attributes. Please report it to the custom component author.

Read about it in the official HA discord server and found this:
"device_state_attributes -> extra_state_attributes, is a name change... its really just that"

**Comment by metbril** [comment]
Thanks for reporting. I will have a look at it.

**Comment by metbril** [comment]
Note to self:

https://github.com/bremor/bureau_of_meteorology/pull/93/

**Comment by metbril** [comment]
Fixed with commit a56aab7364a3d0810283f3429382c8afa92ce65c
