### ISSUE TITLE
Seems like BlueOne95 has been removed from the UC website

### ISSUE THREAD

**Issue by Sjorsa** [metbril/home-assistant-brandstofprijzen#21]
I started getting an error log from this integration since about early November. I just noticed that it's now only receiving 7 values instead of 8, so BlueOne95 is missing, as you can see here as well: https://www.unitedconsumers.com/brandstofprijzen/

I commented out BlueOne95 from my configuration and now everything is fine. Should the documentation be updated to remove BlueOne95? Although it seems like they still track it's price as seen on [this ](https://www.unitedconsumers.com/tanken/informatie/blue-one-95.asp)page.

**Comment by metbril** [comment]
Thanks. I will have a look.

**Comment by metbril** [comment]
Fixed by 9aef39d7f1005b2c03a853d2274cfbd3d58cc916
