### ISSUE TITLE
support for https://carbu.com/

### ISSUE THREAD

**Issue by aaamoeder** [metbril/home-assistant-brandstofprijzen#7]
I LOVE this but would it be possible to add data from https://carbu.com/ ?

Since prices here in Belgium are quite different then the netherlands it would be much more useful.

Thanks for all the work and keep up the good work 👍

**Comment by metbril** [comment]
Thanks for your suggestion!

The Carbu website is different from united consumers. The latter shows average suggested retail prices. Carbo shows prices from specific stations. Those kind of sites are available in the Netherlands, too. But are too difficult to process.

I've found one [page with maximum prices](https://carbu.com//belgie/maximumprijs) that more or less has the same function as United Consumers. Scraping that wouldn't be too difficult.

However, I would like to keep my custom integration limited to the one current website.

You have some alternatives: 

1. copy or clone my repo, and modify it for Carbu yourself, using the maximumprijs page yourself
2. create some scrape sensors in your personal Home Assistant configuration.

I have successfully done this for United Consumers for over a year; the custom component is just a learning exercise.

You can find examples in my repo:

My old, deprecated sensors, still working:

https://github.com/metbril/home-assistant-config/blob/main/packages/mobility/unitedconsumers.yaml.txt

Other sensors for specific fuel stations near my home:

https://github.com/metbril/home-assistant-config/blob/main/packages/mobility/fuel.yaml

**Comment by metbril** [comment]
Since this component will only support United consumers I am closing the issue. 

If you have any questions regarding scraping stations don't hesitate to drop a note.
